### ISSUE TITLE
.product-grid Duplication

### ISSUE THREAD

**Issue by stefkosmo** [Strategery-Inc/Magento-InfiniteScroll#145] opened 2016-03-01 22:39 UTC
Hey,

div .products-grid appears to be duplicated even though the collection returns one set of products.

Any idea why? Please see www.dealicious.co.uk for issue.

Thanks

**Comment by damian-pastorini** [comment] 2016-03-02 20:05
Hi @stefkosmo , when the page load for the first time there's only 1 object loaded:
![image](https://cloud.githubusercontent.com/assets/1211779/13473439/1f14a152-e098-11e5-84d5-22ddbe24768f.png)

And only after I clicked on the "load more" button I get the second set (which is correct):
![image](https://cloud.githubusercontent.com/assets/1211779/13473495/5cd71808-e098-11e5-9f96-a66f5bb01a11.png)

So, if the issue is the "blank space" between the items: 
![image](https://cloud.githubusercontent.com/assets/1211779/13473581/b8f64ba4-e098-11e5-811e-fbf6a4a9f0f1.png)

That's seems to be a problem with your theme becuase there's an extra pixel in the first product of that last row:
![image](https://cloud.githubusercontent.com/assets/1211779/13473611/d57f5e64-e098-11e5-8703-e5db8f5a6c0c.png)

Best,

**Comment by stefkosmo** [comment] 2016-03-03 12:33
Hey, 

Sorry didn't explain myself properly.

I've set the theme to show 12 Products per page. Therefore the "Show more items" should be clicked and display the remaining 3 products, not a duplicate set?

Thanks

**Comment by damian-pastorini** [comment] 2016-03-03 12:59
It seems you have an issue with the pagination because the page two link is returning the page 1 contents:
http://www.dealicious.co.uk/?p=2

**Comment by gsomoza** [comment] 2016-03-03 13:05
Closing this because its not a bug in our extension.

**Closed by gsomoza** 2016-03-03 13:05 UTC

**Comment by stefkosmo** [comment] 2016-03-03 13:40
Ok no problem, thanks anyway.

**Comment by gsomoza** [comment] 2016-03-03 14:10
@stefkosmo if you need help with Magento in general feel free to reach out to us: contact (at) strategery (dot) io

Sorry we can't offer more specific case in situations where the bug is not in our plugin: we offer the plugin for free and therefore we have no budget to offer additional support other than for bug-fixes..

**Comment by stefkosmo** [comment] 2016-03-03 14:45
It's fine thanks. I think the way you provide support at all is great for a free extension. If I can find a fix, ill post an update to any of those who may be in the same situation.

**Comment by gsomoza** [comment] 2016-03-03 17:37
That would be great! We have a small Wiki right here where that kind of information could be very helpful to other users: https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki - feel free to contribute edits to any of those pages.

**Comment by gsomoza** [comment] 2016-03-03 17:38
(or you can always of course just add a comment here if that's easier)
