### ISSUE TITLE
Aheadworks_LayeredNavigation conflict

### ISSUE THREAD

**Issue by AgenceGlanum** [Strategery-Inc/Magento-InfiniteScroll#193] opened 2018-08-21 08:05 UTC
Hi,

We use your module with the Aheadworks_LayredNavigation module. 

When we filter the list and then scroll down, the next products are not loaded. We contacted the Aheadworks support which answered us: "The error occurs with the re-init in 3d party Strategery_Infinitescroll module. Please, contact Strategery developer asking them to give some comments on the following error:
Uncaught Error: Syntax error, unrecognized expression"

You can reproduce the problem on the page http://wotest01.mygreenchapter.com/b2c_en/pot-collections/indoor-pots.html by choosing the D&M Depot brand.

Thanks in advance for your help!

**Comment by gsomoza** [comment] 2018-08-21 08:11
Hi @AgenceGlanum – this is indeed not a problem with the Aheadworks extension: it's rather an integration issue between the two extensions.

We have a few articles that explain [how to solve some common integration issues](https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki/3rd-party-Extension-Conflicts) like the one you're having. You might also want to [read this](https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki/Functionality-Issues-After-Loading-Next-Page).

You'll need a Magento developer to do that.

Close this cause it's not a bug, but feel free to add any other questions.

**Closed by gsomoza** 2018-08-21 08:11 UTC
