### ISSUE TITLE
Uncaught ReferenceError: ConfigurableMediaImages is not defined error Magento 1.9.4.2

### ISSUE THREAD

**Issue by vishy93** [Strategery-Inc/Magento-InfiniteScroll#200] opened 2019-10-04 14:26 UTC
I have been looking to incorporate infinite scrolling into my site. So, when I came across the [InfiniteScroll Magento Plugin by Strategery-Inc][1] I was excited to give it a go.

However, I get the error:

> Uncaught ReferenceError: ConfigurableMediaImages is not defined
    at...

On my theme I do not use Configurable Swatches, backtracking the error the following line is the culprit:    

    ConfigurableMediaImages.setImageFallback(5312, jQuery.parseJSON('[]'));

However, in the file **product-media.js**, at /skin/frontend/rwd/default/js/configurableswatches, I can see it is defined on line 26.

Enabling configurable swatches I get the following error:

        Warning: Invalid argument supplied for foreach()  in /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/ConfigurableSwatches/Helper/Mediafallback.php on line 197
    
    #0 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/ConfigurableSwatches/Helper/Mediafallback.php(197): mageCoreErrorHandler(2, 'Invalid argumen...', '/Applications/X...', 197, Array)
    #1 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/design/frontend/vishlibrex/default/template/strategery/infinitescroll/swatches.phtml(28): Mage_ConfigurableSwatches_Helper_Mediafallback->getConfigurableImagesFallbackArray(Object(Mage_Catalog_Model_Product), Array, true)
    #2 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Block/Template.php(241): include('/Applications/X...')
    #3 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/vishli...')
    #4 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
    #5 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml()
    #6 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/design/frontend/vish/default/template/catalog/product/list.phtml(143): Mage_Core_Block_Abstract->toHtml()
    #7 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Block/Template.php(241): include('/Applications/X...')
    #8 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/vishli...')
    #9 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
    #10 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml()
    #11 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
    #12 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('product_list', true)
    #13 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Catalog/Block/Category/View.php(90): Mage_Core_Block_Abstract->getChildHtml('product_list')
    #14 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/design/frontend/base/default/template/catalog/category/view.phtml(70): Mage_Catalog_Block_Category_View->getProductListHtml()
    #15 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Block/Template.php(241): include('/Applications/X...')
    #16 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/base/d...')
    #17 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
    #18 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml()
    #19 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
    #20 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Text_List->_toHtml()
    #21 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
    #22 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('content', true)
    #23 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/design/frontend/rwd/default/template/page/3columns.phtml(60): Mage_Core_Block_Abstract->getChildHtml('content')
    #24 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Block/Template.php(241): include('/Applications/X...')
    #25 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/rwd/de...')
    #26 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
    #27 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml()
    #28 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
    #29 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
    #30 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Catalog/controllers/CategoryController.php(161): Mage_Core_Controller_Varien_Action->renderLayout()
    #31 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Catalog_CategoryController->viewAction()
    #32 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('view')
    #33 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
    #34 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
    #35 /Applications/XAMPP/xamppfiles/htdocs/mag19/app/Mage.php(687): Mage_Core_Model_App->run(Array)
    #36 /Applications/XAMPP/xamppfiles/htdocs/mag19/index.php(85): Mage::run('', 'store')
    #37 {main}

  [1]: https://github.com/Strategery-Inc/Magento-InfiniteScroll

**Comment by AndresInSpace** [comment] 2019-10-04 15:31
Because https://github.com/Strategery-Inc/Magento-InfiniteScroll/blob/master/app/design/frontend/base/default/layout/strategery-infinitescroll.xml

Doesn't add an If config to the xml including the configurableswatches.. so if you have configswatches disabled, it still trys to add files for them, which are causing your errors. I believe.

**Comment by vishy93** [comment] 2019-10-07 14:21
@AndresInSpace Yeah solution looks to be a simple amendment to:

```
<reference name="product_list.name.after">
            <block type="core/template" name="product_list.infinitescroll">
	        <action method="setTemplate" ifconfig="configswatches/general/enabled">
                        <template>strategery_infinitescroll_swatches.phtml</template>
             </action>
	        </block>
        </reference>
```

**Comment by gsomoza** [comment] 2019-11-25 13:30
@vishy93 that looks like it answers my question on #201 – have you confirmed this works?

**Comment by vishy93** [comment] 2019-11-25 13:42
@gsomoza I can confirm it works :)

**Comment by damian-pastorini** [comment] 2019-11-25 18:01
hi @vishy93 I didn't tested this yet but, why did you also changed the template path? I think we only need to include the ifconfig attribute and that should do the trick or did you moved the template from strategery/infinitescroll ?
I don't recall that M1 replace the underscores to get the proper folder path automatically.
Thanks!

**Comment by vishy93** [comment] 2019-11-25 18:32
@damian-pastorini hey pal, I cannot exactly recall why I changed the template path. I believe it is because I have always followed the underscore convention.

Magento does indeed convert underscores to forward slashes

**Comment by gsomoza** [comment] 2019-11-26 10:03
hmmm, I'm a bit skeptical that it does that conversion in the case of template paths.. @vishy93 if you could change the PR so the template path remains the same as before, that would be great so we can merge your PR quickly. Otherwise, we'll have to wait for @damian-pastorini to do regression testing on these changes.

**Comment by damian-pastorini** [comment] 2019-11-26 11:57
@gsomoza , here:
https://github.com/Strategery-Inc/Magento-InfiniteScroll/pull/203
https://github.com/Strategery-Inc/Magento-InfiniteScroll/pull/204
I'm closing this in favor of the commented PR's.

**Closed by damian-pastorini** 2019-11-26 11:57 UTC

**Comment by vishy93** [comment] 2019-11-26 12:07
@gsomoza Sure will duly amend pr now
