### ISSUE TITLE
All urls show /page/2

### ISSUE THREAD

**Issue by franfuster** [Strategery-Inc/Magento-InfiniteScroll#97] opened 2015-04-10 10:33 UTC
I have installed Strategery InfiniteScroll in a magento 1.7.
When I load a page, It changes automatically my URL from "<base_url>/category" to "<base_url>category/page/2" and only shows products from page1. I go bottom page but not refresh.
I have copied the files in my theme and don't works.
any solution?
thanks

**Comment by gabrielsomoza** [comment] 2015-04-10 11:04
Do you have an online version of your site where we can duplicate the issue and see what's wrong?

**Comment by franfuster** [comment] 2015-04-10 11:15
Yes, my website is http://www.zastor.com and if you enter in a category, you can view the issue 
e.g. http://www.zastor.com/silbatos/

**Comment by gabrielsomoza** [comment] 2015-04-13 10:27
Looks like there might be a conflict with one of your other extensions. We'll take a deeper look to confirm as soon as possible. @damian-pastorini could you do this when you get a chance?

**Comment by damian-pastorini** [comment] 2015-04-13 11:59
@franfuster , you have two instances of jQuery at the same time that could be causing the issues.
jQuery v1.8.3 and v1.10.2.
Also since the scroll is not loading the next page I will recommend you to check the selectors and enable the InfiniteScroll debug mode, that should will give you an idea on where the error could be.

**Comment by franfuster** [comment] 2015-04-14 16:44
Thanks @damian-pastorini,
I disabled the other instance of jquery and check the selectors and the result is the same.
The InfiniteScroll debug mode don't works in frontend.
I disabled "Scroll History" in admin and then dissapear /page/2 from url, but not showing more products when i scroll down in any category or search page.
What can i do?
thanks again,

**Comment by b-d-m-p** [comment] 2015-04-15 02:36
I am having the same exact issue. Since my theme has jQuery, I did not enable jQuery in the settings, but I am still getting the issue even with it not enabled.

**Comment by b-d-m-p** [comment] 2015-04-15 07:09
Yes, I can confirm that if the extension is not enabled that the page/2 error goes away. 

My theme has jQuery so I chose to not enable jQuery in the extension settings, but this page/2 error is there even if the the extension jQuery is disabled. So, I went looking and I found this:

    	jQuery.getScript("http://localhost:8888/js/jquery/infinitescroll/jquery-ias.min.js", function() {
					jQuery(function($) {

It appears to me that this is causing the problem. 

I can just remove it, but is there a better way to fix this? 

Thanks.

**Comment by b-d-m-p** [comment] 2015-04-15 08:35
So, removing that `.getScript("http://localhost:8888/js/jquery/infinitescroll/jquery-ias.min.js"` makes the page/2 error go away, but the extension is still not functioning. I'm not sure if this is due to my theme or some bug in the extension. I'd appreciate any ideas you have. Thanks.

**Comment by franfuster** [comment] 2015-04-15 08:46
Hi @b-d-m-p,
I have tried all you say and the page/2 error go away, but the extension don't works. Same result.
:-(
@damian-pastorini, any solution?
thanks

**Comment by damian-pastorini** [comment] 2015-04-15 11:09
hi @franfuster , my comments about this:
- Checking your theme I found that you have a lot of elements with the container class, if you run jQuery('.category-products') in the console after the page is loaded you will see that there are a lot of hiden blocks with that class. My first recommendation is to use selector that points only to the correct container block, for example you can use jQuery('.category-products:last'), but I would recommend to change the block class or add something to it in order to make it accurate like a second class in the same block, for example jQuery('.category-products.infinitescroll-container').
- If that doesn't fix the issue you should start by checking if other extension is causing the conflict, so you should start by disabling one by one the order extensions and checking the frontend to see if the problem dissapears.
- The extension is based in the jquery-ias.min.js library so if you removed that the InfiniteScroll will never work.

Please let me know if that works. Thanks!

**Comment by franfuster** [comment] 2015-04-15 16:59
Thank You!!! @damian-pastorini
I change the selector to that container block jQuery('.category-products:last'). And then I scroll down and it's show more and more products!! All ok.

**Comment by b-d-m-p** [comment] 2015-04-16 03:08
For me, it was switching local mode to "yes" that fixed the problem.

**Comment by gabrielsomoza** [comment] 2015-04-16 08:14
Alright! Glad this was fixed, thanks to everyone that contributed. @damian-pastorini try to see if we can convert this into a Wiki page for the Troubleshooting / Common Issues section.

**Comment by viniciusrtf** [comment] 2015-06-30 20:20
I could fix this in another way, but I'm still quite confused with this issue. Maybe we should reopen this, but you guys tell me.

First I had the issue in a custom theme on Magento EE 1.14.2. None of the aforementioned solutions worked for me.

Then I reproduced the issue in a test environment:
1- Installed pure Magento 1.9.1.1 + latest Data Sample.
2- Installed Strategy_InfiniteScroll (only extension installed).
3- Inserted near 500 products all in the same category and entered in category product list 
4- Switched from grid (system config default) to list. First time I did this, ?mode=list parameter remained as part of current URL. The InfiniteScroll worked just fine.
5- Second time I try to enter the category (via menu link) mode=list disappears and p=2 appear automatically, and InfiniteScroll stops working.

Even in the test environment, none of the aforementioned solutions worked for me.

What I did was an inspection of Strategery_Infinitescroll_Block_Init, and I couldn't figure out why getProductListMode() only try to get $currentMode from GET parameter, and then from store config. What about catalog/session?

With that in mind I changed

```
if ($currentMode = $this->getRequest()->getParam('mode')) {
```
to
```
if (($currentMode = $this->getRequest()->getParam('mode'))
    || $currentMode = Mage::getSingleton('catalog/session')->getDisplayMode()
) {
```

Applying this patch the issue goes away and infinite scrolling seems to work fine. I tested in CE, EE, default catalog and layered catalog. I couldn't test on catalog search yet.

**Comment by damian-pastorini** [comment] 2015-06-30 21:23
@janmyszkier when you have some time could you take a look on this please?
If we need please apply any fix and just let me know as soon it's done so I could re-package and upload the extension version.
Thanks!

**Comment by janmyszkier** [comment] 2015-06-30 23:30
@viniciusrtf: thanks for looking into this and keeping us posted
@damian-pastorini : I'll be checking on this somewhen today (July 1st)

**Comment by janmyszkier** [comment] 2015-07-08 08:48
@viniciusrtf : thanks for detailed info that allowed me to reproduce the issue:
fix based on the solution you've posted available here for a time being:
https://github.com/janmyszkier/Magento-InfiniteScroll/tree/better_mode_recognition

we'll look into pulling this into master branch soon.
@damian-pastorini: please review

**Comment by damian-pastorini** [comment] 2015-07-08 10:45
PR: https://github.com/Strategery-Inc/Magento-InfiniteScroll/pull/109
:+1:

**Comment by damian-pastorini** [comment] 2016-03-21 19:01
@gsomoza  the PR was merged, we should close this one.

**Closed** 2016-04-25 15:23 UTC
Labels: ready-to-close
