### ISSUE TITLE
INCHOO Featured Products integration

### ISSUE THREAD

**Issue by yuvalmit** [Strategery-Inc/Magento-InfiniteScroll#137] opened 2016-01-31 16:16 UTC
hey,
i'm developing magneto site and i'm using inchoo featured products.
the infinity scroll work great but not on the featured product page :(
is there a way to make it happen? some declaration to do and make the infinity scroll work in that page also?

**Comment by gsomoza** [comment] 2016-02-15 12:15
If the featured product page is not a category page then you'll have to make the integration work manually. Look at how we're using the IAS library in the category pages, and then basically do something similar for the featured product pages. 

(if you're not a developer then you'll need a Magento developer to help you with that)

Closing this ticket for now because its not a bug in our plugin, but we can continue discussing it even while closed.

**Closed by gsomoza** 2016-02-15 12:15 UTC
