### ISSUE TITLE
Double products

### ISSUE THREAD

**Issue by MrBlood** [Strategery-Inc/Magento-InfiniteScroll#189] opened 2018-01-11 18:01 UTC
Everything was working great...  then all of a sudden - (only with infinite scroll ON) --- I get duplicate products and some are missing.  It shows the correct # of products, it's just that some are duplicates...  then some do not show at all.

Again, not sure what happened.  The only difference was that new products were entered.  Have you seen this problem before.  Right now I have it turned off, so normal pagination is working...  but we really love the scroll...  so if you can give me any possible ideas???

Thanks, AB

**Comment by gsomoza** [comment] 2018-01-12 08:58
There are a couple of reasons why something like this could happen:

1. The URL structure changed and now InfinteScroll cannot detect what the URL for the "next" product page is. This is unlikely because we simply retrieve that URL from the pagination itself, so unless the original link is broken InfinteScroll should work with virtually any type of URL.
2. The structure or semantics of the HTML around the pagination changed, so InfinteScroll can't find the pagination controls anymore. E.g. the class name for the "next" link changed.
3.  The InfiniteScroll configuration settings were changed in the Admin, causing InfiniteScroll to not be able to find the "next" pagination link anymore in the HTML.
4. Custom decorating scripts after "next" page-loads (e.g. attached via event listeners on IAS events) are causing the messed up contents to be displayed. A common issue on pages that run lots of decorating logic on the catalog after page-load.

This should be enough information for a developer to investigate and fix the problem. Please refer to our Wiki if you want more details about how things work. Hope this helps!

I'll close this ticket, for now, because this is most likely not a bug on the extension. But if you find that it is, then please feel free to re-open or submit a new ticket with information about how to duplicate the bug.

**Closed by gsomoza** 2018-01-12 08:58 UTC
