### ISSUE TITLE
Mobile not loading when scrolling

### ISSUE THREAD

**Issue by thiagolima-bm** [Strategery-Inc/Magento-InfiniteScroll#164] opened 2016-08-01 23:09 UTC
Hi I am facing problems when scrolling at any mobile device. Sometimes it loads, sometimes not.

**Comment by damian-pastorini** [comment] 2016-08-02 14:57
Hi @thiagolima-bm , could you give us more specifications on the issue?
1 - Could you give a link where we can check the error? 
2 - Do you have a custom theme? 
3 - Did you installed InfiniteScroll last version?
4 - The issue happens on any device or in an specific brand / OS / browser?
5 - Do you have steps to reproduce it consistently?
Any additional information will be appreciated.
Thanks!

**Comment by thiagolima-bm** [comment] 2016-08-04 16:04
@damian-pastorini link http://beta.vixbrasil.com/verao2017/biquinis.chtml
Custom theme; last version; chrome iphone 6; chrome mac (responsive).
You can test at your desktop, the theme is responsible. When you resize the screen, you will see the mobile version.
Thanks

**Comment by damian-pastorini** [comment] 2016-08-08 01:10
Hi @thiagolima-bm , I checked the HTML and InfiniteScroll is not been loaded at all on any of the links in that page.
I tested InfiniteScroll in a base Magento implementation and it worked fine in the mobile devices.
Since this is a free extension and the issue doesn't look like to be in the extension itself but with your custom theme unfortunatelly we can't give you free support.
If you like you can hire our development services so we can assist you with the issue, just email us at contact@strategery.io.
Best,

**Comment by damian-pastorini** [comment] 2016-08-16 13:31
Without any updates, closing the issue.

**Closed by damian-pastorini** 2016-08-16 13:31 UTC
Labels: ready-to-close
