### ISSUE TITLE
Not working with another module

### ISSUE THREAD

**Issue by intheshallow** [Strategery-Inc/Magento-InfiniteScroll#94] opened 2015-02-26 20:19 UTC
I know this is more then likely my problem, but I was just curious to see if you could possibly look into pointing me in the right direction coding wise to get Infinite Scroll to work above the Improved Navigation module? Right now, the Infinite Scroll works for the first time you go to a product list page. But when you use the Improved Navigation on the left, it will revert the search back to the original method.

**Comment by intheshallow** [comment] 2015-02-26 21:58
It has something to do with the ajax side search that they have implemented.

**Comment by gabrielsomoza** [comment] 2015-02-27 10:00
Try to see if this helps - there's a good chance its at least related to it: https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki/Functionality-Issues-After-Loading-Next-Page

**Comment by intheshallow** [comment] 2015-02-27 15:03
Hello,

I see there is an ias_config that I can place options in. I don't know a
whole lot in JavaScript, so I'm not sure what exactly I should place in to
get this to possibly work. At least with the situation I currently I have.
I did notice that you pointed me to this line of code:

this.listeners = { next: new IASCallbacks(), load: new IASCallbacks(),
loaded: new IASCallbacks(), render: new IASCallbacks(), rendered: new
IASCallbacks(), scroll: new IASCallbacks(), noneLeft: new IASCallbacks(),
ready: new IASCallbacks() };
I'm honestly not sure if I just throw this in or need to modify it.




On Fri, Feb 27, 2015 at 5:01 AM, Gabriel Somoza <notifications@github.com>
wrote:

> Try to see if this helps - there's a good chance its at least related to
> it:
> https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki/Functionality-Issues-After-Loading-Next-Page
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Strategery-Inc/Magento-InfiniteScroll/issues/94#issuecomment-76367638>
> .
>



-- 
Corey Luce
Head Web Developer



FRESHLEY MEDIA, INC.
816B ST. ANDREWS BLVD.
CHARLESTON, SC  29407
http://www.freshleymedia.com/

**Comment by gabrielsomoza** [comment] 2015-03-02 09:03
You shouldn't modify that file directly - what you can see there is a list of the events that IAS throws during the scrolling life-cycle. E.g. next, load, loaded, render, etc.

You'd have to hook into those events by providing a callback when IAS is initialised (this is done in your page) and on your listener you'll have to "decorate" the incoming new elements/products with whatever thing the other extension is decorating them (or otherwise "let the other extension know" about the new elements).

I can't help with specifics because I don't know the other extension's functionality. If you want we could have one of our certified developers take a look at this directly on your site for a modest fee. Let me know if you're interested by emailing me at contact (at) strategery (dot) io.

**Comment by gabrielsomoza** [comment] 2015-03-02 09:03
Closing because this is an integration issue and not a bug with our extension.

**Closed by gabrielsomoza** 2015-03-02 09:03 UTC
