### ISSUE TITLE
Multiple Stores Issues

### ISSUE THREAD

**Issue by gsomoza** [Strategery-Inc/Magento-InfiniteScroll#52] opened 2013-11-07 19:48 UTC
We need to re-check how the extension behaves with multiple stores because at least one person told me it wasn't working for them. Here's the email I got:

I am not the developer here, so what I’m about to say could not make sense to you :-)
This is what they did to fix my issue…

app/design/frontend/default/default/layout/strategery-infinitescroll2.xml has been adjusted:

```
<reference name="before_body_end">
<block type="infinitescroll2/config" name="infinitescroll2_config">
<action method="setJsText">
<text>nl/infinitescroll2/js</text>
</action>
</block>
</reference>
```

(under <text>  nl/ was added)”

**Comment by r-martins** [comment] 2015-01-27 11:52
I guess the Block/Config.php is missing. 
I'm experiencing the same problems on multiple store scenario. It loads the ajax but nothing happends.
No js error or anything. Magento 1.8.1 with 1 website, 3 Stores within 1 store view in each store. 

![vspgu2nr3h](https://cloud.githubusercontent.com/assets/191149/5917959/060ef0fa-a60a-11e4-8ad0-0449906695b5.gif)

**Comment by gabrielsomoza** [comment] 2015-01-30 09:26
@nicofff when you get a chance could you check if this is still an issue with the latest IS version?

**Comment by jmmeijer** [comment] 2015-03-07 23:36
I experience the exact same problem on a multistore installation of Magento 1.9.0.1. I am using a custom theme, but also tested on the default theme. The AJAX request get send, the items get returned, however they ar enot put in the DOM. I also tested version 2.0 of AIS. same results.

**Comment by gabrielsomoza** [comment] 2015-03-09 09:55
@damian-pastorini let's look into this asap.

**Comment by jmmeijer** [comment] 2015-03-09 10:05
Thanks, it seems the image urls json response gets misinterpreted somehow. Do the images get loaded before the result is put in the DOM?

**Comment by damian-pastorini** [comment] 2015-03-09 11:29
I recently tested the issue with different configurations in a Magento 1.9.1.
Test 1: 1 website, 1 store, 3 views, using default rwd theme for the 3 views.
Test 2: 1 website, 3 stores, 1 view each, rwd package for the 3 views.
Test 3: 1 website, 3 stores, 1 view each, 2 views with rwd package and 1 view with the default package.
In the 3 tests the infinitescroll works fine.

@r-martins , there's no Block/Config.php in the InfiniteScroll last version, which version are using? I would recommend you to update to the last one.

@jmmeijer , if the items are not been added to the DOM you should check the selectors configuration.

**Comment by jmmeijer** [comment] 2015-03-11 11:08
I checked the selectors, which all seem to be correct (defaults)

    <div class="toolbar">
        <div class="pager">
    ...
            <ol>
    ...
                <li>
                    <a class="next i-next fa fa-caret-right" href="http://beddentotaal.nl/bedtextiel/dekbedovertrekken/mooie-dekbedovertrekken/?p=2" title="Volgende">
                    </a>
                </li>
            </ol>
        </div>
    </div>
    ...
    </div>
            <ul class="products-grid row first odd">
                <li class="item first col-xs-12 col-sm-4">
                ...
                </li>
            </ul>
            <ul class="products-grid row even">
                ...
            </ul>
            ...
    <div class="toolbar-bottom">
        <div class="toolbar">
            <div class="pager">
                ...
            </div>
        </div>
    </div>

**Comment by janmyszkier** [comment] 2015-05-04 09:27
@jmmeijer i just tested this on few different themes I own (and few different magento multistore configs), and I also didn't experience the issue. 
Mind sharing your page or theme with us, that it doesn't work on?

**Comment by damian-pastorini** [comment] 2016-03-21 18:03
I'm closing this since the issue is not in the extension itself.

**Closed by damian-pastorini** 2016-03-21 18:03 UTC
Labels: investigate
