### ISSUE TITLE
Issue with SEO layered navigation.

### ISSUE THREAD

**Issue by athulkvijayan** [Strategery-Inc/Magento-InfiniteScroll#130] opened 2016-01-04 10:03 UTC
I have installed an seo layered navigation extension (catalin seo layered navigation) before installing that extension. the infinite scroll was working fine. After the that it is not working it will show a loading products dialogue and then the page no in the url will be updated but the products are not loading

**Comment by gabrielsomoza** [comment] 2016-01-04 10:04
Probably related [to this](https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki/3rd-party-Extension-Conflicts)?

**Comment by athulkvijayan** [comment] 2016-01-04 10:07
yes. how much time you will require to solve this issue

**Comment by gabrielsomoza** [comment] 2016-01-04 10:12
It depends greatly on the theme and any other extensions, but usually the integration takes between 2 and 5 hours. Very occasionally it could take longer but that would be rare. 

If you'd like one of our developers to do it please emails us at contact (at) strategery (dot) io 

Closing the ticket for now since its not a bug in our extension, but we can continue the discussion anyway.

**Closed by gabrielsomoza** 2016-01-04 10:12 UTC

**Comment by athulkvijayan** [comment] 2016-01-04 10:13
ok thanks for the quick response. I will talk with the team and let you know if they can't fix this issue.
