### ISSUE TITLE
New page not loading

### ISSUE THREAD

**Issue by sunilmandal** [Strategery-Inc/Magento-InfiniteScroll#122] opened 2015-09-18 14:19 UTC
loading image running continuously but data not loaded and in the console the following error is showing
![capture](https://cloud.githubusercontent.com/assets/11804185/9961460/527d95e4-5e3e-11e5-8e14-fb6a87ae77c9.PNG)

**Comment by gabrielsomoza** [comment] 2015-09-18 14:48
@sunilmandal you're running into a know issue caused by another extension. Please refer to this page for more information: https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki/Nothing-Happens,-Although-the-%22Loading-Next-Page%22-Message-is-Visible

Closing this ticket for now - we can re-open later if needed.

**Closed by gabrielsomoza** 2015-09-18 14:48 UTC
